-- Active: 1757555051522@@127.0.0.1@1521@XEPDB1@DEVELOPER
CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200),
    type_document VARCHAR2(20) NOT NULL,
    number_document VARCHAR2(20) NOT NULL UNIQUE,
    phone VARCHAR2(20),
    email VARCHAR2(100),
    birth_date DATE,
    state CHAR(1) CHECK (state IN ('A','I'))
);


DROP TABLE customer;

CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    description VARCHAR2(200),
    category VARCHAR2(100),
    unit_price NUMBER(10,2),
    registration_date DATE,
    state CHAR(1),
    stock NUMBER
);

--ejemplo para la transaccion--
CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(200),
    unit_price NUMBER(10,2) NOT NULL,
    state CHAR(1) CHECK (state IN ('A','I'))
);
  

DROP TABLE product;

CREATE TABLE sale (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    sale_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    total NUMBER(10,2) NOT NULL,
    state CHAR(1) CHECK (state IN ('A','I')),

    CONSTRAINT fk_sale_customer FOREIGN KEY (customer_id) 
        REFERENCES customer(customer_id)
);


CREATE TABLE sale_detail (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id NUMBER NOT NULL,
    id NUMBER NOT NULL,
    quantity NUMBER(10) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    state CHAR(1) CHECK (state IN ('A','I')),

    CONSTRAINT fk_detail_sale FOREIGN KEY (sale_id) 
        REFERENCES sale(id),
    
    CONSTRAINT fk_detail_product FOREIGN KEY (id) 
        REFERENCES product(id)
);

SELECT * FROM customer;
SELECT * FROM product;
SELECT * FROM sale;
SELECT * FROM sale_detail;