-- Active: 1755300079838@@127.0.0.1@1521@XEPDB1@SYSTEM
CREATE TABLE customer (
    customer_id INT IDENTITY(1, 1) PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    address VARCHAR(200) NOT NULL,
    type_document CHAR(3) NOT NULL,
    number_document VARCHAR(15) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(250) NOT NULL,
    birth_date DATE,
    state CHAR(1) NOT NULL
);

USE model;

SELECT * FROM customer;

DROP TABLE customer;

CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    description VARCHAR2(200),
    category VARCHAR2(100),
    unit_price NUMBER(10,2),
    registration_date DATE,
    state CHAR(1),
    stock NUMBER
);
  
SELECT * FROM product;

DROP TABLE product;